before_install:
  - npm install -g mocha istanbul coveralls

language: node_js

node_js:
  - "8"
  - "6"
  - "10"
  
sudo: false

script:
  - "test -z $(npm -g -ps ls istanbul) || npm run-script test-travis"

after_script:
  - "test -e ./coverage/lcov.info && cat ./coverage/lcov.info | coveralls"
